#############################################################################
# Makefile for building: gbcflsh
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  gbcf.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile gbcf.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gbcflsh1.0.0
DISTDIR = /home/cuddy/Projekt/Other\ Stuff/GBFlasher-Software/.tmp/gbcflsh1.0.0
LINK          = g++
LFLAGS        = -static -Wl,-O1
LIBS          = $(SUBLIBS) -Lsrc/lib -L/home/cuddy/Projekt/Other\ Stuff/GBFlasher-Software/src/lib -lftd2xx -lQt5Widgets -lQt5Gui -lQt5Network -lQt5SerialPort -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/About.cpp \
		src/EraseThread.cpp \
		src/gbcflsh.cpp \
		src/Gui.cpp \
		src/Logic.cpp \
		src/ReadFlashThread.cpp \
		src/ReadRamThread.cpp \
		src/Settings.cpp \
		src/WriteFlashThread.cpp \
		src/WriteRamThread.cpp \
		src/USBPortWin.cpp qrc_style.cpp \
		moc_About.cpp \
		moc_AbstractPort.cpp \
		moc_USBPortWin.cpp \
		moc_EraseThread.cpp \
		moc_Gui.cpp \
		moc_Logic.cpp \
		moc_ReadFlashThread.cpp \
		moc_ReadRamThread.cpp \
		moc_Settings.cpp \
		moc_WriteFlashThread.cpp \
		moc_WriteRamThread.cpp
OBJECTS       = About.o \
		EraseThread.o \
		gbcflsh.o \
		Gui.o \
		Logic.o \
		ReadFlashThread.o \
		ReadRamThread.o \
		Settings.o \
		WriteFlashThread.o \
		WriteRamThread.o \
		USBPortWin.o \
		qrc_style.o \
		moc_About.o \
		moc_AbstractPort.o \
		moc_USBPortWin.o \
		moc_EraseThread.o \
		moc_Gui.o \
		moc_Logic.o \
		moc_ReadFlashThread.o \
		moc_ReadRamThread.o \
		moc_Settings.o \
		moc_WriteFlashThread.o \
		moc_WriteRamThread.o
DIST          = src/lib/ftd2xx.lib \
		src/icon.xpm \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		gbcf.pro src/About.h \
		src/AbstractPort.h \
		src/Console.h \
		src/USBPortWin.h \
		src/const.h \
		src/EraseThread.h \
		src/Gui.h \
		src/Logic.h \
		src/ReadFlashThread.h \
		src/ReadRamThread.h \
		src/Settings.h \
		src/WriteFlashThread.h \
		src/WriteRamThread.h \
		src/WinTypes.h \
		src/about.xpm \
		src/ftd2xx.h \
		src/icon.xpm src/About.cpp \
		src/EraseThread.cpp \
		src/gbcflsh.cpp \
		src/Gui.cpp \
		src/Logic.cpp \
		src/ReadFlashThread.cpp \
		src/ReadRamThread.cpp \
		src/Settings.cpp \
		src/WriteFlashThread.cpp \
		src/WriteRamThread.cpp \
		src/USBPortWin.cpp
QMAKE_TARGET  = gbcflsh
DESTDIR       = 
TARGET        = gbcflsh


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gbcf.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		gbcf.pro \
		qdarkstyle/style.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5SerialPort.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile gbcf.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
gbcf.pro:
qdarkstyle/style.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5SerialPort.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile gbcf.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qdarkstyle/style.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/About.h src/AbstractPort.h src/Console.h src/USBPortWin.h src/const.h src/EraseThread.h src/Gui.h src/Logic.h src/ReadFlashThread.h src/ReadRamThread.h src/Settings.h src/WriteFlashThread.h src/WriteRamThread.h src/WinTypes.h src/about.xpm src/ftd2xx.h src/icon.xpm $(DISTDIR)/
	$(COPY_FILE) --parents src/About.cpp src/EraseThread.cpp src/gbcflsh.cpp src/Gui.cpp src/Logic.cpp src/ReadFlashThread.cpp src/ReadRamThread.cpp src/Settings.cpp src/WriteFlashThread.cpp src/WriteRamThread.cpp src/USBPortWin.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_style.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_style.cpp
qrc_style.cpp: qdarkstyle/style.qrc \
		/usr/lib/qt5/bin/rcc \
		qdarkstyle/rc/transparent.png \
		qdarkstyle/rc/line_horizontal_pressed.png \
		qdarkstyle/rc/line_horizontal.png \
		qdarkstyle/rc/arrow_left_disabled@2x.png \
		qdarkstyle/rc/branch_more_focus.png \
		qdarkstyle/rc/arrow_down_disabled@2x.png \
		qdarkstyle/rc/toolbar_move_vertical_pressed.png \
		qdarkstyle/rc/window_close_pressed@2x.png \
		qdarkstyle/rc/arrow_up_focus.png \
		qdarkstyle/rc/toolbar_separator_horizontal_pressed@2x.png \
		qdarkstyle/rc/window_close_pressed.png \
		qdarkstyle/rc/branch_open_disabled@2x.png \
		qdarkstyle/rc/line_horizontal_focus@2x.png \
		qdarkstyle/rc/genericarrow.png \
		qdarkstyle/rc/checkbox_unchecked.png \
		qdarkstyle/rc/radio_checked_focus@2x.png \
		qdarkstyle/rc/checkbox_checked_pressed@2x.png \
		qdarkstyle/rc/base_icon_disabled.png \
		qdarkstyle/rc/toolbar_move_horizontal.png \
		qdarkstyle/rc/window_close_disabled.png \
		qdarkstyle/rc/branch_line@2x.png \
		qdarkstyle/rc/toolbar_move_vertical@2x.png \
		qdarkstyle/rc/arrow_right_pressed@2x.png \
		qdarkstyle/rc/arrow_up_disabled.png \
		qdarkstyle/rc/checkbox_checked@2x.png \
		qdarkstyle/rc/toolbar_move_vertical_focus.png \
		qdarkstyle/rc/radio_unchecked_disabled.png \
		qdarkstyle/rc/checkbox_indeterminate.png \
		qdarkstyle/rc/window_close_disabled@2x.png \
		qdarkstyle/rc/window_grip_pressed@2x.png \
		qdarkstyle/rc/toolbar_separator_horizontal_focus@2x.png \
		qdarkstyle/rc/branch_closed_disabled.png \
		qdarkstyle/rc/branch_line.png \
		qdarkstyle/rc/checkbox_indeterminate_pressed.png \
		qdarkstyle/rc/transparent_focus.png \
		qdarkstyle/rc/toolbar_separator_horizontal.png \
		qdarkstyle/rc/branch_end_focus.png \
		qdarkstyle/rc/checkbox_unchecked@2x.png \
		qdarkstyle/rc/window_undock_disabled.png \
		qdarkstyle/rc/radio_checked_pressed@2x.png \
		qdarkstyle/rc/branch_end_focus@2x.png \
		qdarkstyle/rc/toolbar_move_horizontal_focus.png \
		qdarkstyle/rc/arrow_left_focus.png \
		qdarkstyle/rc/arrow_left@2x.png \
		qdarkstyle/rc/toolbar_separator_vertical_focus@2x.png \
		qdarkstyle/rc/window_grip_focus@2x.png \
		qdarkstyle/rc/window_undock_focus.png \
		qdarkstyle/rc/window_close.png \
		qdarkstyle/rc/line_horizontal@2x.png \
		qdarkstyle/rc/toolbar_move_vertical_disabled@2x.png \
		qdarkstyle/rc/line_vertical_focus@2x.png \
		qdarkstyle/rc/arrow_right@2x.png \
		qdarkstyle/rc/base_icon_pressed.png \
		qdarkstyle/rc/branch_line_focus.png \
		qdarkstyle/rc/window_grip_focus.png \
		qdarkstyle/rc/arrow_right_disabled@2x.png \
		qdarkstyle/rc/branch_more_pressed@2x.png \
		qdarkstyle/rc/toolbar_move_vertical_disabled.png \
		qdarkstyle/rc/arrow_up.png \
		qdarkstyle/rc/arrow_left_pressed@2x.png \
		qdarkstyle/rc/checkbox_checked.png \
		qdarkstyle/rc/toolbar_move_horizontal_disabled.png \
		qdarkstyle/rc/line_vertical_pressed.png \
		qdarkstyle/rc/base_icon_pressed@2x.png \
		qdarkstyle/rc/toolbar_separator_vertical_focus.png \
		qdarkstyle/rc/branch_end_pressed.png \
		qdarkstyle/rc/checkbox_indeterminate_focus@2x.png \
		qdarkstyle/rc/window_minimize_disabled.png \
		qdarkstyle/rc/window_undock_pressed.png \
		qdarkstyle/rc/radio_checked@2x.png \
		qdarkstyle/rc/toolbar_move_horizontal_disabled@2x.png \
		qdarkstyle/rc/branch_closed_disabled@2x.png \
		qdarkstyle/rc/line_vertical.png \
		qdarkstyle/rc/branch_line_disabled.png \
		qdarkstyle/rc/toolbar_separator_vertical.png \
		qdarkstyle/rc/branch_more_disabled.png \
		qdarkstyle/rc/toolbar_move_horizontal@2x.png \
		qdarkstyle/rc/window_undock_disabled@2x.png \
		qdarkstyle/rc/arrow_down_pressed.png \
		qdarkstyle/rc/toolbar_separator_horizontal_disabled@2x.png \
		qdarkstyle/rc/branch_more_disabled@2x.png \
		qdarkstyle/rc/line_vertical_focus.png \
		qdarkstyle/rc/toolbar_separator_horizontal@2x.png \
		qdarkstyle/rc/arrow_left_focus@2x.png \
		qdarkstyle/rc/transparent_focus@2x.png \
		qdarkstyle/rc/branch_open_focus@2x.png \
		qdarkstyle/rc/toolbar_separator_vertical_disabled@2x.png \
		qdarkstyle/rc/arrow_down_focus@2x.png \
		qdarkstyle/rc/arrow_up_pressed@2x.png \
		qdarkstyle/rc/arrow_up_disabled@2x.png \
		qdarkstyle/rc/checkbox_checked_disabled.png \
		qdarkstyle/rc/checkbox_checked_disabled@2x.png \
		qdarkstyle/rc/line_vertical@2x.png \
		qdarkstyle/rc/window_close@2x.png \
		qdarkstyle/rc/arrow_right_disabled.png \
		qdarkstyle/rc/branch_open@2x.png \
		qdarkstyle/rc/checkbox_unchecked_focus@2x.png \
		qdarkstyle/rc/line_vertical_disabled@2x.png \
		qdarkstyle/rc/branch_more.png \
		qdarkstyle/rc/transparent_pressed@2x.png \
		qdarkstyle/rc/toolbar_move_vertical.png \
		qdarkstyle/rc/line_horizontal_focus.png \
		qdarkstyle/rc/window_minimize_focus.png \
		qdarkstyle/rc/checkbox_indeterminate@2x.png \
		qdarkstyle/rc/branch_end_pressed@2x.png \
		qdarkstyle/rc/arrow_up_pressed.png \
		qdarkstyle/rc/arrow_right.png \
		qdarkstyle/rc/radio_checked_disabled@2x.png \
		qdarkstyle/rc/branch_open_pressed.png \
		qdarkstyle/rc/line_horizontal_disabled.png \
		qdarkstyle/rc/window_close_focus.png \
		qdarkstyle/rc/radio_checked_disabled.png \
		qdarkstyle/rc/branch_more@2x.png \
		qdarkstyle/rc/branch_open.png \
		qdarkstyle/rc/checkbox_unchecked_disabled@2x.png \
		qdarkstyle/rc/base_icon_focus@2x.png \
		qdarkstyle/rc/checkbox_unchecked_pressed.png \
		qdarkstyle/rc/window_close_focus@2x.png \
		qdarkstyle/rc/window_minimize_pressed@2x.png \
		qdarkstyle/rc/branch_closed.png \
		qdarkstyle/rc/arrow_up_focus@2x.png \
		qdarkstyle/rc/radio_checked_pressed.png \
		qdarkstyle/rc/branch_end_disabled@2x.png \
		qdarkstyle/rc/radio_unchecked_disabled@2x.png \
		qdarkstyle/rc/radio_unchecked_focus@2x.png \
		qdarkstyle/rc/base_icon@2x.png \
		qdarkstyle/rc/toolbar_move_vertical_pressed@2x.png \
		qdarkstyle/rc/toolbar_separator_vertical_pressed.png \
		qdarkstyle/rc/toolbar_separator_horizontal_disabled.png \
		qdarkstyle/rc/branch_line_disabled@2x.png \
		qdarkstyle/rc/branch_closed_pressed.png \
		qdarkstyle/rc/branch_closed_focus@2x.png \
		qdarkstyle/rc/window_minimize@2x.png \
		qdarkstyle/rc/window_minimize.png \
		qdarkstyle/rc/transparent_pressed.png \
		qdarkstyle/rc/window_grip@2x.png \
		qdarkstyle/rc/checkbox_indeterminate_pressed@2x.png \
		qdarkstyle/rc/base_icon_focus.png \
		qdarkstyle/rc/checkbox_checked_pressed.png \
		qdarkstyle/rc/arrow_down_focus.png \
		qdarkstyle/rc/radio_checked.png \
		qdarkstyle/rc/branch_end_disabled.png \
		qdarkstyle/rc/toolbar_move_horizontal_pressed.png \
		qdarkstyle/rc/radio_unchecked_focus.png \
		qdarkstyle/rc/window_undock_focus@2x.png \
		qdarkstyle/rc/radio_unchecked_pressed.png \
		qdarkstyle/rc/toolbar_separator_vertical_disabled.png \
		qdarkstyle/rc/window_undock.png \
		qdarkstyle/rc/window_grip_disabled.png \
		qdarkstyle/rc/branch_open_pressed@2x.png \
		qdarkstyle/rc/radio_checked_focus.png \
		qdarkstyle/rc/checkbox_checked_focus.png \
		qdarkstyle/rc/window_undock_pressed@2x.png \
		qdarkstyle/rc/line_vertical_disabled.png \
		qdarkstyle/rc/checkbox_unchecked_focus.png \
		qdarkstyle/rc/branch_closed_focus.png \
		qdarkstyle/rc/arrow_down@2x.png \
		qdarkstyle/rc/toolbar_move_vertical_focus@2x.png \
		qdarkstyle/rc/toolbar_separator_horizontal_focus.png \
		qdarkstyle/rc/window_grip_disabled@2x.png \
		qdarkstyle/rc/radio_unchecked.png \
		qdarkstyle/rc/checkbox_unchecked_pressed@2x.png \
		qdarkstyle/rc/window_grip.png \
		qdarkstyle/rc/toolbar_separator_vertical@2x.png \
		qdarkstyle/rc/arrow_right_focus.png \
		qdarkstyle/rc/toolbar_move_horizontal_focus@2x.png \
		qdarkstyle/rc/transparent_disabled@2x.png \
		qdarkstyle/rc/base_icon_disabled@2x.png \
		qdarkstyle/rc/window_grip_pressed.png \
		qdarkstyle/rc/base_icon.png \
		qdarkstyle/rc/transparent@2x.png \
		qdarkstyle/rc/arrow_up@2x.png \
		qdarkstyle/rc/line_vertical_pressed@2x.png \
		qdarkstyle/rc/line_horizontal_disabled@2x.png \
		qdarkstyle/rc/window_minimize_disabled@2x.png \
		qdarkstyle/rc/checkbox_indeterminate_disabled.png \
		qdarkstyle/rc/window_minimize_focus@2x.png \
		qdarkstyle/rc/window_undock@2x.png \
		qdarkstyle/rc/checkbox_indeterminate_disabled@2x.png \
		qdarkstyle/rc/branch_line_pressed@2x.png \
		qdarkstyle/rc/branch_line_focus@2x.png \
		qdarkstyle/rc/branch_line_pressed.png \
		qdarkstyle/rc/window_minimize_pressed.png \
		qdarkstyle/rc/radio_unchecked@2x.png \
		qdarkstyle/rc/checkbox_indeterminate_focus.png \
		qdarkstyle/rc/branch_closed_pressed@2x.png \
		qdarkstyle/rc/arrow_left.png \
		qdarkstyle/rc/toolbar_separator_vertical_pressed@2x.png \
		qdarkstyle/rc/branch_more_focus@2x.png \
		qdarkstyle/rc/line_horizontal_pressed@2x.png \
		qdarkstyle/rc/branch_more_pressed.png \
		qdarkstyle/rc/arrow_right_pressed.png \
		qdarkstyle/rc/arrow_down_pressed@2x.png \
		qdarkstyle/rc/toolbar_separator_horizontal_pressed.png \
		qdarkstyle/rc/branch_closed@2x.png \
		qdarkstyle/rc/branch_end@2x.png \
		qdarkstyle/rc/arrow_left_disabled.png \
		qdarkstyle/rc/transparent_disabled.png \
		qdarkstyle/rc/branch_open_disabled.png \
		qdarkstyle/rc/branch_open_focus.png \
		qdarkstyle/rc/arrow_down_disabled.png \
		qdarkstyle/rc/radio_unchecked_pressed@2x.png \
		qdarkstyle/rc/branch_end.png \
		qdarkstyle/rc/checkbox_unchecked_disabled.png \
		qdarkstyle/rc/checkbox_checked_focus@2x.png \
		qdarkstyle/rc/arrow_left_pressed.png \
		qdarkstyle/rc/arrow_down.png \
		qdarkstyle/rc/toolbar_move_horizontal_pressed@2x.png \
		qdarkstyle/rc/arrow_right_focus@2x.png \
		qdarkstyle/style.qss
	/usr/lib/qt5/bin/rcc -name style qdarkstyle/style.qrc -o qrc_style.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_About.cpp moc_AbstractPort.cpp moc_USBPortWin.cpp moc_EraseThread.cpp moc_Gui.cpp moc_Logic.cpp moc_ReadFlashThread.cpp moc_ReadRamThread.cpp moc_Settings.cpp moc_WriteFlashThread.cpp moc_WriteRamThread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_About.cpp moc_AbstractPort.cpp moc_USBPortWin.cpp moc_EraseThread.cpp moc_Gui.cpp moc_Logic.cpp moc_ReadFlashThread.cpp moc_ReadRamThread.cpp moc_Settings.cpp moc_WriteFlashThread.cpp moc_WriteRamThread.cpp
moc_About.cpp: src/About.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/About.h -o moc_About.cpp

moc_AbstractPort.cpp: src/AbstractPort.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/AbstractPort.h -o moc_AbstractPort.cpp

moc_USBPortWin.cpp: src/AbstractPort.h \
		src/ftd2xx.h \
		src/WinTypes.h \
		src/USBPortWin.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/USBPortWin.h -o moc_USBPortWin.cpp

moc_EraseThread.cpp: src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/EraseThread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/EraseThread.h -o moc_EraseThread.cpp

moc_Gui.cpp: src/Settings.h \
		src/const.h \
		src/Console.h \
		src/Logic.h \
		src/AbstractPort.h \
		src/About.h \
		src/ReadFlashThread.h \
		src/WriteFlashThread.h \
		src/EraseThread.h \
		src/ReadRamThread.h \
		src/WriteRamThread.h \
		src/Gui.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui.h -o moc_Gui.cpp

moc_Logic.cpp: src/const.h \
		src/AbstractPort.h \
		src/Logic.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Logic.h -o moc_Logic.cpp

moc_ReadFlashThread.cpp: src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/ReadFlashThread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/ReadFlashThread.h -o moc_ReadFlashThread.cpp

moc_ReadRamThread.cpp: src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/ReadRamThread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/ReadRamThread.h -o moc_ReadRamThread.cpp

moc_Settings.cpp: src/const.h \
		src/Settings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Settings.h -o moc_Settings.cpp

moc_WriteFlashThread.cpp: src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/WriteFlashThread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/WriteFlashThread.h -o moc_WriteFlashThread.cpp

moc_WriteRamThread.cpp: src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/WriteRamThread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/cuddy/Projekt/Other Stuff/GBFlasher-Software/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I'/home/cuddy/Projekt/Other Stuff/GBFlasher-Software' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/WriteRamThread.h -o moc_WriteRamThread.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

About.o: src/About.cpp src/About.h \
		src/about.xpm \
		src/const.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o About.o src/About.cpp

EraseThread.o: src/EraseThread.cpp src/EraseThread.h \
		src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EraseThread.o src/EraseThread.cpp

gbcflsh.o: src/gbcflsh.cpp src/Gui.h \
		src/Settings.h \
		src/const.h \
		src/Console.h \
		src/Logic.h \
		src/AbstractPort.h \
		src/About.h \
		src/ReadFlashThread.h \
		src/WriteFlashThread.h \
		src/EraseThread.h \
		src/ReadRamThread.h \
		src/WriteRamThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gbcflsh.o src/gbcflsh.cpp

Gui.o: src/Gui.cpp src/Gui.h \
		src/Settings.h \
		src/const.h \
		src/Console.h \
		src/Logic.h \
		src/AbstractPort.h \
		src/About.h \
		src/ReadFlashThread.h \
		src/WriteFlashThread.h \
		src/EraseThread.h \
		src/ReadRamThread.h \
		src/WriteRamThread.h \
		src/USBPortWin.h \
		src/ftd2xx.h \
		src/WinTypes.h \
		src/icon.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Gui.o src/Gui.cpp

Logic.o: src/Logic.cpp src/Logic.h \
		src/const.h \
		src/AbstractPort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Logic.o src/Logic.cpp

ReadFlashThread.o: src/ReadFlashThread.cpp src/ReadFlashThread.h \
		src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReadFlashThread.o src/ReadFlashThread.cpp

ReadRamThread.o: src/ReadRamThread.cpp src/ReadRamThread.h \
		src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReadRamThread.o src/ReadRamThread.cpp

Settings.o: src/Settings.cpp src/Settings.h \
		src/const.h \
		src/Gui.h \
		src/Console.h \
		src/Logic.h \
		src/AbstractPort.h \
		src/About.h \
		src/ReadFlashThread.h \
		src/WriteFlashThread.h \
		src/EraseThread.h \
		src/ReadRamThread.h \
		src/WriteRamThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settings.o src/Settings.cpp

WriteFlashThread.o: src/WriteFlashThread.cpp src/WriteFlashThread.h \
		src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WriteFlashThread.o src/WriteFlashThread.cpp

WriteRamThread.o: src/WriteRamThread.cpp src/WriteRamThread.h \
		src/AbstractPort.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WriteRamThread.o src/WriteRamThread.cpp

USBPortWin.o: src/USBPortWin.cpp src/const.h \
		src/USBPortWin.h \
		src/AbstractPort.h \
		src/ftd2xx.h \
		src/WinTypes.h \
		src/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o USBPortWin.o src/USBPortWin.cpp

qrc_style.o: qrc_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_style.o qrc_style.cpp

moc_About.o: moc_About.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_About.o moc_About.cpp

moc_AbstractPort.o: moc_AbstractPort.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AbstractPort.o moc_AbstractPort.cpp

moc_USBPortWin.o: moc_USBPortWin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_USBPortWin.o moc_USBPortWin.cpp

moc_EraseThread.o: moc_EraseThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EraseThread.o moc_EraseThread.cpp

moc_Gui.o: moc_Gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Gui.o moc_Gui.cpp

moc_Logic.o: moc_Logic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Logic.o moc_Logic.cpp

moc_ReadFlashThread.o: moc_ReadFlashThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ReadFlashThread.o moc_ReadFlashThread.cpp

moc_ReadRamThread.o: moc_ReadRamThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ReadRamThread.o moc_ReadRamThread.cpp

moc_Settings.o: moc_Settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Settings.o moc_Settings.cpp

moc_WriteFlashThread.o: moc_WriteFlashThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WriteFlashThread.o moc_WriteFlashThread.cpp

moc_WriteRamThread.o: moc_WriteRamThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WriteRamThread.o moc_WriteRamThread.cpp

####### Install

install_exec: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(QINSTALL_PROGRAM) /home/cuddy/Projekt/Other\ Stuff/GBFlasher-Software/gbcflsh $(INSTALL_ROOT)/usr/bin/gbcflsh

uninstall_exec: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/bin/gbcflsh
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install: install_exec  FORCE

uninstall: uninstall_exec  FORCE

FORCE:

